config/routes.rb
Rails.application.routes.draw do
  resources :feeds do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :favorites, only: [:create, :destroy, :index]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :feed
end

app/models/feed.rb
class Feed < ApplicationRecord
    mount_uploader :image, ImageUploader
    validates :image, presence: true
    validates :text, presence: true
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true, length: { maximum: 30 }
    validates :email, presence: true, length: { maximum: 255 },
              format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    before_validation { email.downcase! }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    has_many :feeds
    mount_uploader :image, ImageUploader
    validates :image, presence: true
    has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
    before_action :login_required
    def authenticate_user
        if @current_user == nil
           flash[:notice] = t('notice.ログインしてください')
           redirect_to new_session_path
        end
    end

    def fobid_login_user
        if @current_user
          flash[:notice]="ログインしています"
          redirect_to user_show
        end
    end
    private
    def login_required
        redirect_to new_session_path unless current_user
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
        favorite = current_user.favorites.create(feed_id: params[:feed_id])
        redirect_to feeds_path, notice: "#{favorite.feed.user.name}さんのブログをお気に入り登録しました"
    end

    def destroy
        favorite = current_user.favorites.find_by(id: params[:id]).destroy
        redirect_to feeds_path, notice: "#{favorite.feed.user.name}さんのブログをお気に入り解除しました"
    end

    def index
        @favorites = Favorite.all
    end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :logged_in?, only:[:new,:create]
  before_action :set_feed, only: %i[ show edit update destroy ]
  before_action :block_other_user, only: [:edit, :update, :destroy]

  def index
    @feeds = Feed.all
  end

  def show
    @favorite = current_user.favorites.find_by(feed_id: @feed.id)
  end

  def new
    @feed = Feed.new
  end

  def confirm
    @feed = Feed.new(feed_params)
  end
  
  def edit
  end
  
  def create
    @feed = current_user.feeds.build(feed_params)   
    respond_to do |format|
      if @feed.save
        ContactMailer.contact_mail(@feed).deliver
        format.html { redirect_to feeds_path, notice: "Feed was successfully created." }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: "Feed was successfully updated." }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: "Feed was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def set_feed
    @feed = Feed.find(params[:id])
  end
  def feed_params
    params.require(:feed).permit(:image, :image_cache, :text)
  end
  def block_other_user
    if current_user.id != @feed.user_id
      redirect_to feeds_path, notice:"投稿者ではありません"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in?, only:[:new,:create]
  skip_before_action :login_required, only: [:new, :create]

    def new
        @user = User.new
    end
    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to user_path(@user.id)
        else
          render :new
        end
    end
    def show
        @user = User.find(params[:id])
    end
    def edit
        @user = User.find(params[:id])
    end
    def update
        @user = User.find(params[:id])
        respond_to do |format|
          if @user.update(user_params)
            format.html { redirect_to @user, notice: "プロフィールを編集しました." }
            format.json { render :show, status: :ok, location: @user }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        end
    end
    private
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache)
    end

    def set_user
      @user = User.find(params[:id])
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def choose_new_or_edit
    if action_name == 'new'
      confirm_feeds_path
    elsif action_name == 'edit'
      feed_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def logged_in?
        current_user.present?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<h1>お気に入り一覧</h1>

<div class = table>
  <table>
    <thead>
      <tr>
        <th>投稿者</th>
        <th>画像</th>
        <th>投稿内容</th>
      </tr>
    </thead>
    <tbody>
      <% @favorites.each do |favorite| %>
        <tr>
          <td><%= favorite.feed.user.name %></td>
          <td><%= image_tag favorite.feed.image.url %></td>
          <td><%= favorite.feed.text %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/feeds/_form.html.erb
<%= form_with(model: @feed, local: true, url: choose_new_or_edit) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %>
    <%= form.hidden_field :image_cache %>
    <%= form.label :text %>
    <%= form.text_field :text %>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/confirm.html.erb
<h1>投稿確認画面</h1>
<div class = "posting-check">
  <%= form_with(model: @feed, url: feeds_path, local: true) do |form| %>
    <strong>Text:</strong>
    <%= @feed.text%>
    <%= form.hidden_field :text %>
    <p><strong>Image:</strong>
    <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %>
    <%= form.hidden_field :image_cache %></p>  
    <%= form.submit "投稿する" %>
  <% end %>
  <%= form_with(model:@feed, url:new_feed_path, local:true, method:"get") do |form| %>
    <%= form.hidden_field :image_cache %>
    <%= form.submit "戻る", name: "back" %>
  <% end %>
</div>

app/views/feeds/edit.html.erb
<h1>編集する</h1>
<div class = "editing">
    <%= render 'form', feed: @feed %>
</div>
<div class = "btn-center">
    <%= link_to 'Show', @feed %> |
    <%= link_to 'Back', feeds_path %>
</div>

app/views/feeds/index.html.erb
<h1>投稿一覧ページ</h1>

<div class = "table">
  <table >
    <thead>
      <tr>
        <th>User</th>
        <th>Text</th>
        <th>Image</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @feeds.each do |feed| %>
        <tr>
          <th><%= feed.user.name%></th>
          <th><%= feed.text%></th>
          <td><%= image_tag feed.image.url %></td>
          <td><%= link_to '詳細', feed %></td>
          <% if current_user.id == feed.user_id %>
            <td><%= link_to '編集', edit_feed_path(feed.id) %></td>
            <td><%= link_to '削除', feed, method: :delete, data: { confirm: '本当に削除してもよろしいですか?' } %></td>
          <% end %>
       </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>投稿する</h1>
<div class = "new-posting">
  <%= render 'form', feed: @feed %>
  <%= link_to '投稿一覧へ', feeds_path %></p>
</div>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

  <p class = "dateil-top">
    <strong>Text :</strong>
    <%= @feed.text%>
  </p>
  <p class = "dateil-bottom">
    <strong>Image :</strong>
    <%= image_tag @feed.image.url %>
  </p>
  <% unless @feed.user_id == current_user.id %>
    <% if @favorite.present? %>
      <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to 'お気に入りする', favorites_path(feed_id: @feed.id), method: :post, class: 'btn btn-primary' %>
    <% end %>
  <% end %>
<div class = "btn-center">
  <%= link_to 'Edit', edit_feed_path(@feed) %> |
  <%= link_to 'Back', feeds_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Instagram</h1>
    </header>
    <div class= "header-logo">
          <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "#{key}") %>
          <% end %>
          <% if logged_in? %>
            <%= link_to "Profile", user_path(current_user.id) %>
            <%= link_to "Logout", session_path(current_user.id), method: :delete %>
            <%= link_to "投稿する", new_feed_path %>
            <%= link_to "投稿一覧", feeds_path %>
            <%= link_to "お気に入り", favorites_path %>
          <% else %>
            <%= link_to "Sign up", new_user_path %>
            <%= link_to "Login", new_session_path %>
          <% end %>
     </div>

    <%= yield %>
    
    <footer>
      <h1>@2021 DIVE INTO CODE</h1>
    </footer>
  </body>
</html>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class = "signup">
  <%= form_with(model: @user, local: true) do |f| %>  
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= f.label :image %>
    <%= f.file_field :image %>  
    <p><%= f.submit "編集" %></p>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>編集する</h1>
<div class = "profile-editing">
    <%= render 'form', user: @user %>
</div>
<%= link_to 'Back', user_path %>

app/views/users/new.html.erb
<h1>新規登録</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class = "signup">
  <%= form_with(model: @user, local: true) do |f| %>  
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= f.label :image %>
    <%= f.file_field :image %>  
    <p><%= f.submit "アカウントを新規登録する" %></p>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>プロフィール</h1>
<h1><%= @user.name %>のページ</h1>
<p class = "after-login">メールアドレス: <%= @user.email %></p>
<div class = "profile">
<p>プロフィール画像</p>
<%=image_tag @user.image.url %>
<p><%= link_to 'プロフィールを編集する', edit_user_path(@user) %></p> 
</div>